# Generated by Django 5.0.6 on 2024-06-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_payment_pay_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_method',
            field=models.CharField(choices=[('cash', 'Наличными'), ('transfer', 'Перевод на счет')], max_length=10, verbose_name='способ оплаты'),
        ),
    ]
